# {{project.name}}

Generated using **create-cheers2sun-app**.

---

## Quick Start

```bash
npm install

npm run dev
```

---

## Generated Features

- Next.js
- TypeScript
- Duffel Integration
- Supabase Integration

---

## Project Structure

```
app/
components/
src/
public/
```

---

Generated by Cheers2Sun.
