import "./globals.css";

import { ReactNode } from "react";

export const metadata = {
    title: "{{PROJECT_NAME}}",
    description: "Generated by Cheers2Sun"
};

export default function RootLayout({
    children
}: {
    children: ReactNode;
}) {

    return (

        <html lang="en">

            <body>

                {children}

            </body>

        </html>

    );

}
