export default function Home() {

    return (

        <main>

            <h1>

                Welcome to {{PROJECT_NAME}}

            </h1>

            <p>

                Generated by Cheers2Sun

            </p>

        </main>

    );

}
