export default function HomePage() {

    return (

        <main>

            <h1>

                Welcome to {{project.name}}

            </h1>

            <p>

                Generated by Cheers2Sun

            </p>

        </main>

    );

}
