import * as fs from "node:fs";
import * as path from "node:path";

import { CheersContext } from "../compiler/CheersContext";

export class CheersGenerator {

    public generate(context: CheersContext): void {

        console.log("Generating project...");

        this.createOutputFolder(context.output);

        this.createReadme(context);

        console.log("Generation completed.");

    }

    private createOutputFolder(output: string): void {

        if (!fs.existsSync(output)) {

            fs.mkdirSync(output, {
                recursive: true
            });

        }

    }

    private createReadme(context: CheersContext): void {

        const readme = `# ${context.spec.project.name}

Generated by Cheers2Sun Compiler

Specification Version: ${context.spec.version}

Application: ${context.spec.application.domain}

Template: ${context.spec.application.template}
`;

        fs.writeFileSync(
            path.join(context.output, "README.md"),
            readme,
            "utf8"
        );

    }

}
